CommonServices:
  systematicsHistogram: 'listOfSystematics'
  fixDAODTruthRecord: False
  enableExpertMode: True # this is ONLY because of disabling nnjvt tool for METMaker https://mattermost.web.cern.ch/atlas-jetetmiss/pl/4yb7b8g9h3rj5kr8s6kppi6bxe

PileupReweighting: {}

Jets:
  - containerName: 'AnaJets'
    jetCollection: 'AntiKt4EMTopoJets' # Not recommended to use different container selections than AnaJets.baselineJvt.
    runJvtSelection: False
    #runJvtUpdate: True
    runJvtEfficiency: False
    PtEtaSelection:
        minPt: 25000.0
        maxEta: 2.5
    #FlavourTagging:
    #  - btagger: 'GN2v01'
    #    btagWP: 'FixedCutBEff_85'
    #    bTagCalibFile: '/cvmfs/atlas.cern.ch/repo/sw/database/GroupData/xAODBTaggingEfficiency/13p6TeV/MC23_2024-10-17_GN2v01_v1.root'
    #    noEffSF: True
    #  - btagger: 'DL1dv01' #'GN2v01'
    #    btagWP: 'FixedCutBEff_85'
    #    bTagCalibFile: '/cvmfs/atlas.cern.ch/repo/sw/database/GroupData/xAODBTaggingEfficiency/13p6TeV/MC23_2024-10-17_GN2v01_v1.root'
    #    noEffSF: True
    #  - btagger: 'DL1dv01' #'GN2v01'
    #    btagWP: 'FixedCutBEff_77'
    #    bTagCalibFile: '/cvmfs/atlas.cern.ch/repo/sw/database/GroupData/xAODBTaggingEfficiency/13p6TeV/MC23_2024-10-17_GN2v01_v1.root'
    #    noEffSF: True
    #  - btagger: 'DL1dv01' #'GN2v01'
    #    btagWP: 'FixedCutBEff_70'
    #    bTagCalibFile: '/cvmfs/atlas.cern.ch/repo/sw/database/GroupData/xAODBTaggingEfficiency/13p6TeV/MC23_2024-10-17_GN2v01_v1.root'
    #    noEffSF: True
    #  - btagger: 'DL1dv01' #'GN2v01'
    #    btagWP: 'FixedCutBEff_60' #'FixedCutBEff_65'
    #    bTagCalibFile: '/cvmfs/atlas.cern.ch/repo/sw/database/GroupData/xAODBTaggingEfficiency/13p6TeV/MC23_2024-10-17_GN2v01_v1.root'
    #    noEffSF: True
    #  - btagger: 'DL1dv01' #'GN2v01'
    #    btagWP: 'Continuous'
    #    bTagCalibFile: '/cvmfs/atlas.cern.ch/repo/sw/database/GroupData/xAODBTaggingEfficiency/13p6TeV/MC23_2024-10-17_GN2v01_v1.root'
    #FlavourTaggingEventSF:
    #  - containerName: 'AnaJets'#.baselineJvt'
    #    btagger: 'GN2v01'
    #    btagWP: 'Continuous'
  - containerName: 'EMPFlowJets'
    jetCollection: 'AntiKt4EMPFlowJets'
    PtEtaSelection:
        minPt: 25000.0
        maxEta: 2.5
    Uncertainties:
        systematicsModelJES: 'Category'
        systematicsModelJER: 'Full'
    FlavourTagging:
      - btagger: 'GN2v01'
        btagWP: 'Continuous'
      - btagger: 'GN2v01'
        btagWP: 'FixedCutCEff_50'
        useCTagging: True
      - btagger: 'GN2v01'
        btagWP: 'FixedCutCEff_30'
        useCTagging: True
      - btagger: 'GN2v01'
        btagWP: 'FixedCutCEff_10'
        useCTagging: True
      - btagger: 'GN2v01'
        btagWP: 'Continuous2D'
    FlavourTaggingEventSF:
      - containerName: 'EMPFlowJets'
        btagger: 'GN2v01'
        btagWP: 'Continuous2D'


Electrons:
  - containerName: 'AnaElectrons'
    crackVeto: True
    IFFClassification: {}
    writeTrackD0Z0: True
    ESModel: ''
    WorkingPoint:
      - selectionName: 'loose'
        identificationWP: 'TightLH'
        isolationWP: 'NonIso'
        trackSelection: True
        #noEffSF: True
      - selectionName: 'tight'
        identificationWP: 'TightLH'
        isolationWP: 'Tight_VarRad'
        trackSelection: True
        #noEffSF: True
    PtEtaSelection:
        minPt: 27000.0
        maxEta: 2.47
        useClusterEta: True

Muons:
  - containerName: 'AnaMuons'
    IFFClassification: {}
    writeTrackD0Z0: True
    WorkingPoint:
      - selectionName: 'loose'
        quality: 'Medium'
        isolation: 'NonIso'
        trackSelection: True
      - selectionName: 'tight'
        quality: 'Medium'
        isolation: 'Tight_VarRad'
        systematicBreakdown: True
        trackSelection: True
    PtEtaSelection:
        minPt: 25000.0
        maxEta: 2.5

InDetTracks:
  - inputContainer: 'InDetTrackParticles'
    containerName: 'AnaTracks'
    runBiasing: False
    minPt: 500
    maxEta: 2.5
    outputTrackSummaryInfo: True
    

MissingET:
  - containerName: 'AnaMET'
    jets: 'AnaJets'
    electrons: 'AnaElectrons.tight'
    muons: 'AnaMuons.tight'
    useJVT: False
    # the following is needed to overwrite the settings when using EMTopo jets (do not have NNJVT)
    # mind the usage of enableExpertMode in the CommonServices above
    propertyOverrides: {
      "MetMakerAlg.makerTool.JetSelection": "Expert",
      "MetMakerAlg.makerTool.CustomJetJvtWP": "None"
    }

# Note: so far, OR done against EMTopo jets only
OverlapRemoval:
  inputLabel: 'preselectOR'
  outputLabel: 'passesOR'
  jets: 'AnaJets'#.baselineJvt'
  electrons: 'AnaElectrons.tight'
  muons: 'AnaMuons.tight'
  #enableUserPriority: False

ObjectCutFlow:
  - containerName: 'AnaElectrons'
    selectionName: 'tight'
  #- containerName: 'AnaJets'
  #  selectionName: 'baselineJvt'
  - containerName: 'AnaMuons'
    selectionName: 'tight'

Thinning:
  - containerName: 'AnaJets'
    outputName: 'OutJets'
    #selectionName: 'baselineJvt'
  - containerName: 'AnaElectrons'
    outputName: 'OutElectrons'
    selectionName: 'tight||loose'
  - containerName: 'AnaMuons'
    outputName: 'OutMuons'
    selectionName: 'tight||loose'
  - containerName: 'EMPFlowJets'
    outputName: 'OutPFlowJets'
  - containerName: 'AnaTracks'
    outputName: 'OutTracks'

Trigger:
    triggerChainsPerYear: # is a dictionary that sets up trigger selection + matching, triggerChainsForSelection is a list that sets up trigger selection only
        '2015':
            - 'HLT_e24_lhmedium_L1EM20VH || HLT_e60_lhmedium || HLT_e120_lhloose || HLT_e140_lhloose_nod0'
            - 'HLT_mu20_iloose_L1MU15 || HLT_mu40'
        '2016':
            - 'HLT_e26_lhtight_nod0_ivarloose || HLT_e60_lhmedium_nod0 || HLT_e300_etcut'
            - 'HLT_mu26_ivarmedium || HLT_mu50 || HLT_mu60_0eta105_msonly'
        '2017':
            - 'HLT_e26_lhtight_nod0_ivarloose || HLT_e60_lhmedium_nod0 || HLT_e300_etcut'
            - 'HLT_mu26_ivarmedium || HLT_mu50 || HLT_mu60_0eta105_msonly'
        '2018':
            - 'HLT_e60_lhmedium_nod0 || HLT_e26_lhtight_nod0_ivarloose || HLT_e300_etcut'
            - 'HLT_mu26_ivarmedium || HLT_mu50 || HLT_mu60_0eta105_msonly'
        '2022':
            - 'HLT_e26_lhtight_ivarloose_L1EM22VHI || HLT_e60_lhmedium_L1EM22VHI || HLT_e140_lhloose_L1EM22VHI'
            - 'HLT_mu24_ivarmedium_L1MU14FCH || HLT_mu50_L1MU14FCH'
            ##### all calratio chains following, similar for 2022, 23, 24
            - 'HLT_j30_CLEANllp_momemfrac006_calratio_L1jJ160'
            - 'HLT_j30_CLEANllp_momemfrac006_calratiormbib_L1jJ160'
            # Calratio backup for jJ160
            - 'HLT_j30_CLEANllp_momemfrac006_calratio_L1eTAU140'
            - 'HLT_j30_CLEANllp_momemfrac006_calratiormbib_L1eTAU140'
            - 'HLT_j30_CLEANllp_momemfrac006_calratio_L1eTAU80'
            - 'HLT_j30_CLEANllp_momemfrac006_calratiormbib_L1eTAU80'
            # Calratio Legacy support chains
            - 'HLT_j30_CLEANllp_momemfrac006_calratio_L1eTAU60_EMPTY'
            - 'HLT_j30_CLEANllp_momemfrac006_calratiormbib_L1eTAU60_EMPTY'
            - 'HLT_j30_CLEANllp_momemfrac006_calratio_L1eTAU60_UNPAIRED_ISO'       
            # new version of triggers with pileup recalculation, should be prescaled 
            - 'HLT_j30_CLEANllp_momemfrac012_calratiovar_roiftf_preselj20emf12_L1jJ160'
            # Calratio LLP-NoMATCH analogs
            - 'HLT_j30_CLEANllp_momemfrac006_calratio_L1eTAU40HT'
            - 'HLT_j30_CLEANllp_momemfrac006_calratiormbib_L1eTAU40HT'
            - 'HLT_j30_CLEANllp_momemfrac006_calratio_L1eTAU60HM'
            - 'HLT_j30_CLEANllp_momemfrac006_calratiormbib_L1eTAU60HM'
        '2023':
            - 'HLT_e26_lhtight_ivarloose_L1eEM26M || HLT_e60_lhmedium_L1eEM26M || HLT_e140_lhloose_L1eEM26M'
            - 'HLT_mu24_ivarmedium_L1MU14FCH || HLT_mu50_L1MU14FCH'
            ##### all calratio chains following, similar for 2022, 23, 24
            - 'HLT_j30_CLEANllp_momemfrac006_calratio_L1jJ160'
            - 'HLT_j30_CLEANllp_momemfrac006_calratiormbib_L1jJ160'
            # Calratio backup for jJ160
            - 'HLT_j30_CLEANllp_momemfrac006_calratio_L1eTAU140'
            - 'HLT_j30_CLEANllp_momemfrac006_calratiormbib_L1eTAU140'
            - 'HLT_j30_CLEANllp_momemfrac006_calratio_L1eTAU80'
            - 'HLT_j30_CLEANllp_momemfrac006_calratiormbib_L1eTAU80'
            # Calratio Legacy support chains
            - 'HLT_j30_CLEANllp_momemfrac006_calratio_L1eTAU60_EMPTY'
            - 'HLT_j30_CLEANllp_momemfrac006_calratiormbib_L1eTAU60_EMPTY'
            - 'HLT_j30_CLEANllp_momemfrac006_calratio_L1eTAU60_UNPAIRED_ISO'       
            # new version of triggers with pileup recalculation, should be prescaled 
            - 'HLT_j30_CLEANllp_momemfrac012_calratiovar_roiftf_preselj20emf12_L1jJ160'
            # Calratio LLP-NoMATCH analogs
            - 'HLT_j30_CLEANllp_momemfrac006_calratio_L1eTAU40HT'
            - 'HLT_j30_CLEANllp_momemfrac006_calratiormbib_L1eTAU40HT'
            - 'HLT_j30_CLEANllp_momemfrac006_calratio_L1eTAU60HM'
            - 'HLT_j30_CLEANllp_momemfrac006_calratiormbib_L1eTAU60HM'
        '2024':
            - 'HLT_e26_lhtight_ivarloose_L1eEM26M || HLT_e60_lhmedium_L1eEM26M || HLT_e140_lhloose_L1eEM26M'
            - 'HLT_mu24_ivarmedium_L1MU14FCH || HLT_mu50_L1MU14FCH'
            ##### all calratio chains following, similar for 2022, 23, 24
            - 'HLT_j30_CLEANllp_momemfrac006_calratio_L1jJ160'
            - 'HLT_j30_CLEANllp_momemfrac006_calratiormbib_L1jJ160'
            # Calratio backup for jJ160
            - 'HLT_j30_CLEANllp_momemfrac006_calratio_L1eTAU140'
            - 'HLT_j30_CLEANllp_momemfrac006_calratiormbib_L1eTAU140'
            - 'HLT_j30_CLEANllp_momemfrac006_calratio_L1eTAU80'
            - 'HLT_j30_CLEANllp_momemfrac006_calratiormbib_L1eTAU80'
            # Calratio Legacy support chains
            - 'HLT_j30_CLEANllp_momemfrac006_calratio_L1eTAU60_EMPTY'
            - 'HLT_j30_CLEANllp_momemfrac006_calratiormbib_L1eTAU60_EMPTY'
            - 'HLT_j30_CLEANllp_momemfrac006_calratio_L1eTAU60_UNPAIRED_ISO'       
            # new version of triggers with pileup recalculation, should be prescaled 
            - 'HLT_j30_CLEANllp_momemfrac012_calratiovar_roiftf_preselj20emf12_L1jJ160'
            # Calratio LLP-NoMATCH analogs
            - 'HLT_j30_CLEANllp_momemfrac006_calratio_L1eTAU40HT'
            - 'HLT_j30_CLEANllp_momemfrac006_calratiormbib_L1eTAU40HT'
            - 'HLT_j30_CLEANllp_momemfrac006_calratio_L1eTAU60HM'
            - 'HLT_j30_CLEANllp_momemfrac006_calratiormbib_L1eTAU60HM'

    noGlobalTriggerEff: True
    electrons: 'AnaElectrons.tight'
    electronID: 'Tight'
    electronIsol: 'Tight_VarRad'
    muons: 'AnaMuons.tight'
    muonID: 'Medium'
    #muonIsol: 'TightTrackOnly_VarRad'
    noFilter: True

EventCleaning:
  runEventCleaning: False
  runGRL: True
  userGRLFiles:
    - 'GoodRunsLists/data22_13p6TeV/20250321/data22_13p6TeV.periodAllYear_DetStatus-v134-pro28-09_MERGED_PHYS_StandardGRL_All_Good_25ns.xml'
    - 'GoodRunsLists/data23_13p6TeV/20250321/data23_13p6TeV.periodAllYear_DetStatus-v133-pro31-11_MERGED_PHYS_StandardGRL_All_Good_25ns.xml'
    - 'GoodRunsLists/data24_13p6TeV/20241118/physics_25ns_data24.xml'
    - 'GoodRunsLists/data25_13p6TeV/20260129/physics_25ns_data25_periodsDEFKMOQ.xml'
  GRLDict: {}

# ToDo: for different signatures, cf. Marion + Frederic mods.
EventSelection:
  - electrons: 'AnaElectrons.loose'
    muons: 'AnaMuons.tight'
    jets: 'AnaJets'#.baselineJvt'
    met: 'AnaMET'
    #btagDecoration: 'ftag_select_GN2v01_FixedCutBEff_85'
    noFilter: True 
    cutFlowHistograms: True
    selectionCutsDict: 
      'charmingALP_ttbar_ALP_semilep': |
        SUM_EL_N_MU_N tight tight 27000 25000 == 1
        MET >= 30000
        MET+MWT >= 50000
        JET_N 25000 >= 3
        SAVE
      'DisplacedTop_Hss': |
        JET_N 70000 >= 2
        JET_N 80000 >= 1
        SAVE


# ToDo: revisit and split into reco and truth
TopCalRatio: 
- electrons: 'AnaElectrons'
  muons: 'AnaMuons'
  met: 'AnaMET'
  topojets: 'AnaJets'
  empflowjets: 'EMPFlowJets'
  indettracks: 'AnaTracks'
  selection: 'pass_charmingALP_ttbar_ALP_semilep_%SYS%,as_char||pass_DisplacedTop_Hss_%SYS%,as_char'
  priVtx: 'PrimaryVertices'
  secVtx: 'VrtSecInclusive_SecondaryVertices'


GeneratorLevelAnalysis:
- saveCutBookkeepers: True


LeptonSF:
- muons: 'AnaMuons.tight'
  lepton_postfix: 'tight'


# After configuring each container, many variables will be saved automatically.
Output:
  treeName: 'reco'
  vars:
    - 'EventInfo.lumiBlock -> lumiBlock'

    # AntiKt4EMTopoJetsAuxDyn
    # this can change based on sys?
    - 'OutJets_%SYS%.SumPtTrkPt500 -> EMTopoJet_sumPtTrk_%SYS%'
    - 'OutJets_%SYS%.DFCommonJets_jetClean_LooseBadLLP -> EMTopoJet_isClean_LooseBadLLP_%SYS%'
    - 'OutJets_%SYS%.NumTrkPt500 -> EMTopoJet_NumTrkPt500_%SYS%'
    
    # AntiKt4EMPFlowJetsAuxDyn
    - 'OutPFlowJets_%SYS%.SumPtTrkPt500 -> EMPFlowJet_sumPtTrk_%SYS%'
    - 'OutPFlowJets_%SYS%.DFCommonJets_jetClean_LooseBadLLP -> EMPFlowJet_isClean_LooseBadLLP_%SYS%'
    - 'OutPFlowJets_%SYS%.NumTrkPt500 -> EMPFlowJet_NumTrkPt500_%SYS%'

    # for now just nominal, not sure if more than that needed here
    - 'PrimaryVertices.vertexType -> priVtx_type'
    - 'PrimaryVertices.x -> priVtx_x'
    - 'PrimaryVertices.y -> priVtx_y'
    - 'PrimaryVertices.z -> priVtx_z'
    - 'PrimaryVertices.trackParticleLinks -> priVtx_vertexTrackParticleLinks'
    - 'PrimaryVertices.vertexLinkToInDetTrackParticle -> priVtx_vertexLinkToInDetTrackParticle type=unsigned'

    - 'VrtSecInclusive_SecondaryVertices.vertexType -> secVtx_type'
    - 'VrtSecInclusive_SecondaryVertices.x -> secVtx_x'
    - 'VrtSecInclusive_SecondaryVertices.y -> secVtx_y'
    - 'VrtSecInclusive_SecondaryVertices.z -> secVtx_z'
    - 'VrtSecInclusive_SecondaryVertices.trackParticleLinks -> secVtx_vertexTrackParticleLinks'
    - 'VrtSecInclusive_SecondaryVertices.vertexLinkToInDetTrackParticle -> secVtx_vertexLinkToInDetTrackParticle type=unsigned'

  metVars: []
  containers:
      # Format should follow: '<suffix>:<output container>'
      el_: 'OutElectrons'
      mu_: 'OutMuons'
      EMTopoJet_: 'OutJets'
      EMPFlowJet_: 'OutPFlowJets'
      met_: 'AnaMET'
      trk_: 'OutTracks'
      '': 'EventInfo'
      priVtx_: 'PrimaryVertices'
      secVtx_: 'VrtSecInclusive_SecondaryVertices'

  commands:
    # Turn output branches on and off with 'enable' and 'disable'
    #- disable EMTopoJet_.*_eff.*
    # this can not be disabled anymore, as it does not even exist given expert mode changes above
    #- disable EMTopoJet_jvtEfficiency.*
    - disable EMPFlowJet_jvtEfficiency.*

AddConfigBlocks:
    - modulePath: 'TopCalRatio.TopCalRatioConfig'
      functionName: 'TopCalRatioConfig'
      algName: 'TopCalRatio'
      pos: 'Output'
